const ContractDefs = {
  auditDAO_ABI: [
    "function stake(uint256 amount) external",
    "function unstake(uint256 amount) external",
    "function claimRewards() external",
    "function submitCommunityProposal(uint256 proposalId, bytes32 resultHash) external",
    "function vote(uint256 proposalId, bytes32 proposalHash, uint256 voteAmount) external",
    "function submitTeamReport(uint256 proposalId, bytes32 reportHash) external",
    "function createProposal(bytes32 codeHash) external returns (uint256)",
    "function startCommunityReview(uint256 proposalId) external",
    "function startVoting(uint256 proposalId) external",
    "function startVoting(uint256 proposalId, uint256 _votingDuration) external",
    "function finalizeVoting(uint256 proposalId) external",
    "function initiateVeto(uint256 proposalId, string calldata evidence) external",
    "function committeeReviewVeto(uint256 proposalId, bool supportVeto) external",
    "function setAuditTeam(address _auditTeam) external",
    "function setCommitteeMembers(address[] calldata _members) external",
    "function setCommitteeRewardPenaltyRates(uint256 _rewardRate, uint256 _penaltyRate) external",
    "function setMinStakeAmount(uint256 _amount) external",
    "function setVoteRewardPenaltyRates(uint256 _rewardRate, uint256 _penaltyRate) external",
    "function setMinArbitrationDeposit(uint256 _deposit) external",
    "function setDisputeRetentionPeriod(uint256 _period) external",
    "function setDefaultVotingDuration(uint256 _duration) external",
    "function allocateRewards(address recipient, uint256 amount) external",
    "function slashStake(address staker, uint256 amount) external",
    "function applyVoteRewardsPenalties(uint256 proposalId, bytes32 finalHash) external",
    "function transferOwnership(address newOwner) external",
    "function getProposalSummary(uint256 proposalId) external view returns (tuple(uint256 id, bytes32 codeHash, bytes32 auditReportHash, bytes32 winningCommunityHash, bytes32 secondReviewHash, uint8 status, uint8 riskLevel, uint256 createdAt, uint256 disputeCreatedAt, bool arbitrationRequested, bool vetoRequested, bool vetoApproved))",
    "function getStakerInfo(address staker) external view returns (uint256 balance, uint256 rewards, uint256 contributionPoints, uint256 reputationScore)",
    "function getCommunityProposalVotes(uint256 proposalId, bytes32 hash) external view returns (uint256)",
    "function getCommunityProposalHashes(uint256 proposalId) external view returns (bytes32[])",
    "function claimProposal(uint256 proposalId, uint256 teamId) external",
    "function isProposalClaimed(uint256 proposalId) external view returns (bool)",
    "function isProposalUnassigned(uint256 proposalId) external view returns (bool)",
    "function getUnassignedProposals() external view returns (uint256[] memory)",
    "function voteRewardsApplied(uint256 proposalId) external view returns (bool)",
    "function auditTeam() external view returns (address)",
    "function owner() external view returns (address)",
    "function teamManager() external view returns (address)",
    "function isCommitteeMember(address member) external view returns (bool)",
    "function getCommitteeMembers() external view returns (address[] memory)",
    "function defaultVotingDuration() external view returns (uint256)",
    "function committeeRewardRate() external view returns (uint256)",
    "function committeePenaltyRate() external view returns (uint256)",
    "function minStakeAmount() external view returns (uint256)"
  ],

  teamManager_ABI: [
    "function getActiveAuditTeams() external view returns (uint256[] memory)",
    "function getAuditTeam(uint256 teamId) external view returns (uint256, address, string, uint256, uint256, uint256, address[], bool, uint256)",
    "function getTeamAccuracy(uint256 teamId) external view returns (uint256)",
    "function registerAuditTeam(string calldata name, address teamContract, address[] calldata members) external returns (uint256)",
    "function deactivateAuditTeam(uint256 teamId) external",
    "function addAuditTeamMember(uint256 teamId, address newMember) external",
    "function removeAuditTeamMember(uint256 teamId, address memberToRemove) external"
  ],

  ceatToken_ABI: [
    "function approve(address spender, uint256 amount) external returns (bool)",
    "function allowance(address owner, address spender) external view returns (uint256)",
    "function balanceOf(address account) external view returns (uint256)",
    "function decimals() external view returns (uint8)",
    "function symbol() external view returns (string)",
    "function buyCEAT() external payable",
    "function transfer(address to, uint256 amount) external returns (bool)",
    "function transferFrom(address from, address to, uint256 amount) external returns (bool)"
  ]
};
